{{- if .Values.apisix.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: apisix-routes-job
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: register-routes
          image: quay.io/curl/curl:8.1.2
          command: [ "/bin/sh", "-c", "/bin/create-routes.sh" ]
          volumeMounts:
            - name: apisix-routes
              mountPath: /bin/create-routes.sh
              subPath: create-routes.sh
      volumes:
        - name: apisix-routes
          configMap:
            name: apisix-routes
            defaultMode: 0755

      restartPolicy: Never
  backoffLimit: 10
{{- end }}