{{- $existing := lookup "v1" "Secret" $.Release.Namespace .Values.authentication.generatePasswords.secretName }}
{{- if .Values.authentication.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.authentication.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  mysql-root-password:
    {{- if $existing }}
      {{ index $existing.data "mysql-root-password" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
  mysql-replication-password:
    {{- if $existing }}
      {{ index $existing.data "mysql-replication-password" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
  mysql-password:
    {{- if $existing }}
      {{ index $existing.data "mysql-password" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
{{- end }}