{{- $existing := lookup "v1" "Secret" $.Release.Namespace .Values.postgresql.generatePasswords.secretName }}
{{- if .Values.postgresql.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgresql.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  postgres-user-password:
    {{- if $existing }}
      {{ index $existing.data "postgres-user-password" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
  postgres-admin-password:
    {{- if $existing }}
      {{ index $existing.data "postgres-admin-password" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
{{- end }}