{{- if .Values.postgresql.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.postgresql.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  postgres-user-password: {{ randAlphaNum 30 | b64enc | quote }}
  postgres-admin-password: {{ randAlphaNum 30 | b64enc | quote }}
  {{- if (eq .Values.postgresql.auth.enablePostgresUser true) }}
  postgres-user: {{ postgres | b64enc | quote }}  
  {{- end }}  
{{- end }}