#
  #  Copyright (c) 2025 Cofinity-X
  #  Copyright (c) 2025 Contributors to the Eclipse Foundation
  #
  #  See the NOTICE file(s) distributed with this work for additional
  #  information regarding copyright ownership.
  #
  #  This program and the accompanying materials are made available under the
  #  terms of the Apache License, Version 2.0 which is available at
  #  https://www.apache.org/licenses/LICENSE-2.0
  #
  #  Unless required by applicable law or agreed to in writing, software
  #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  #  License for the specific language governing permissions and limitations
  #  under the License.
  #
  #  SPDX-License-Identifier: Apache-2.0
  #

---
{{- if (eq .Values.identityhub.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: identityhub-service
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    app.kubernetes.io/name: identityhub
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.identityhub.service.type }}
  ports:
    - port: {{ .Values.identityhub.endpoints.default.port }}
      targetPort: default
      protocol: TCP
      name: default
    - port: {{ .Values.identityhub.endpoints.identity.port }}
      targetPort: identity
      protocol: TCP
      name: identity
    - port: {{ .Values.identityhub.endpoints.did.port }}
      targetPort: did
      protocol: TCP
      name: did
    - port: {{ .Values.identityhub.endpoints.credentials.port }}
      targetPort: credentials
      protocol: TCP
      name: credentials
    - port: {{ .Values.identityhub.endpoints.version.port }}
      targetPort: version
      protocol: TCP
      name: version
    - port: {{ .Values.identityhub.endpoints.sts.port }}
      targetPort: sts
      protocol: TCP
      name: sts
  selector:
    app.kubernetes.io/name: identityhub
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}