#
  #  Copyright (c) 2025 Cofinity-X
  #  Copyright (c) 2025 LKS Next
  #  Copyright (c) 2025 Contributors to the Eclipse Foundation
  #
  #  See the NOTICE file(s) distributed with this work for additional
  #  information regarding copyright ownership.
  #
  #  This program and the accompanying materials are made available under the
  #  terms of the Apache License, Version 2.0 which is available at
  #  https://www.apache.org/licenses/LICENSE-2.0
  #
  #  Unless required by applicable law or agreed to in writing, software
  #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  #  License for the specific language governing permissions and limitations
  #  under the License.
  #
  #  SPDX-License-Identifier: Apache-2.0
  #

---
{{- if (eq .Values.identityhub.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityhub
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    app.kubernetes.io/name: identityhub
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if not .Values.identityhub.autoscaling.enabled }}
  replicas: {{ .Values.identityhub.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: identityhub
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.identityhub.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: identityhub
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.identityhub.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      securityContext:
        {{- toYaml .Values.identityhub.podSecurityContext | nindent 8 }}
      {{- if .Values.identityhub.deployment.initContainers }}
      initContainers:
        {{- with .Values.identityhub.deployment.initContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.identityhub.securityContext | nindent 12 }}
          # either use the specified image, or use the default one
          {{- if .Values.identityhub.image.repository }}
          image: "{{ .Values.identityhub.image.repository }}:{{ .Values.identityhub.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "tractusx/identityhub:{{ .Values.identityhub.image.tag | default .Chart.AppVersion }}"
          {{- end }}

          imagePullPolicy: {{ .Values.identityhub.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.identityhub.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.identityhub.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.identityhub.endpoints.default.path }}/check/liveness
              port: {{ .Values.identityhub.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.identityhub.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.identityhub.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.identityhub.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.identityhub.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.identityhub.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.identityhub.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.identityhub.endpoints.default.path }}/check/readiness
              port: {{ .Values.identityhub.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.identityhub.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.identityhub.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.identityhub.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.identityhub.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.identityhub.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.identityhub.resources | nindent 12 }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -Dhttps.proxyHost=squid-proxy.infra.svc.cluster.local
                -Dhttps.proxyPort=8888
                -Dhttp.proxyHost=squid-proxy.infra.svc.cluster.local
                -Dhttp.proxyPort=8888
                -Dhttp.nonProxyHosts="*-vault|*.cluster.local"
                -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
            - name: EDC_DATASOURCE_PARTICIPANTCONTEXT_PASSWORD
              {{- if .Values.identityhub.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.postgresql.auth.existingSecret }}
                  key: {{ .Values.identityhub.postgresql.auth.existingSecretPasswordKey }}                
              {{- else }}
              value: {{ .Values.identityhub.postgresql.auth.password | quote }}
              {{- end }}
            - name: EDC_DATASOURCE_KEYPAIR_PASSWORD
              {{- if .Values.identityhub.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.postgresql.auth.existingSecret }}
                  key: {{ .Values.identityhub.postgresql.auth.existingSecretPasswordKey }}                
              {{- else }}
              value: {{ .Values.identityhub.postgresql.auth.password | quote }}
              {{- end }}
            - name: EDC_DATASOURCE_STSCLIENT_PASSWORD
              {{- if .Values.identityhub.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.postgresql.auth.existingSecret }}
                  key: {{ .Values.identityhub.postgresql.auth.existingSecretPasswordKey }}                
              {{- else }}
              value: {{ .Values.identityhub.postgresql.auth.password | quote }}
              {{- end }}
            - name: EDC_DATASOURCE_CREDENTIALREQUEST_PASSWORD
              {{- if .Values.identityhub.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.postgresql.auth.existingSecret }}
                  key: {{ .Values.identityhub.postgresql.auth.existingSecretPasswordKey }}                
              {{- else }}
              value: {{ .Values.identityhub.postgresql.auth.password | quote }}
              {{- end }}
            - name: EDC_DATASOURCE_CREDENTIALS_PASSWORD
              {{- if .Values.identityhub.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.postgresql.auth.existingSecret }}
                  key: {{ .Values.identityhub.postgresql.auth.existingSecretPasswordKey }}                
              {{- else }}
              value: {{ .Values.identityhub.postgresql.auth.password | quote }}
              {{- end }}
            - name: EDC_DATASOURCE_JTI_PASSWORD
              {{- if .Values.identityhub.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.postgresql.auth.existingSecret }}
                  key: {{ .Values.identityhub.postgresql.auth.existingSecretPasswordKey }}                
              {{- else }}
              value: {{ .Values.identityhub.postgresql.auth.password | quote }}
              {{- end }}
            - name: EDC_DATASOURCE_DIDRESOURCE_PASSWORD
              {{- if .Values.identityhub.postgresql.auth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.identityhub.postgresql.auth.existingSecret }}
                  key: {{ .Values.identityhub.postgresql.auth.existingSecretPasswordKey }}                
              {{- else }}
              value: {{ .Values.identityhub.postgresql.auth.password | quote }}
              {{- end }}
            - name: EDC_IH_API_SUPERUSER_KEY
              value: c3VwZXItdXNlcg==.random
          


            ######################################
            ## Additional environment variables ##
            ######################################
          {{- range $key, $value := .Values.identityhub.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.identityhub.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or .Values.identityhub.envSecretNames .Values.identityhub.envConfigMapNames) (or (gt (len .Values.identityhub.envSecretNames) 0) (gt (len .Values.identityhub.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.identityhub.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.identityhub.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.identityhub.customCaCerts }}
            - name: custom-cacerts
              mountPath: /opt/java/openjdk/lib/security/cacerts
              subPath: cacerts
            {{- end }}
            - name: "tmp"
              mountPath: "/tmp"
            - name : configuration
              mountPath: /app/logging.properties
              subPath: logging.properties
            - name: logs
              mountPath: {{ .Values.identityhub.logging.path }}
            {{- if .Values.identityhub.deployment.additionalVolumeMounts }}
            {{- with .Values.identityhub.deployment.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.identityhub.deployment.additionalVolumes }}
        {{- with .Values.identityhub.deployment.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        - name: "configuration"
          configMap:
            name: identityhub-logging
            items:
              - key: "logging.properties"
                path: "logging.properties"
        {{- if .Values.identityhub.customCaCerts }}
        - name: custom-cacertificates
          configMap:
            name: identityhub-custom-cacerts
            defaultMode: 0400
        - name: custom-cacerts
          emptyDir:
            sizeLimit: 1Mi
        {{- end }}
        - name: "tmp"
          emptyDir: { }
        - name: logs # aim for persistent volume in localhost
        {{- if and .Values.identityhub.logging.enabled .Values.identityhub.logging.persistence.enabled }}
          persistentVolumeClaim:
            claimName: identityhub-pvc-logs
        {{- else }}
          emptyDir: { }
        {{- end }}
      {{- with .Values.identityhub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.identityhub.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.identityhub.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}