{{- $existing := lookup "v1" "Secret" $.Release.Namespace .Values.issuance.generatePasswords.secretName }}
{{- if .Values.issuance.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.issuance.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  keycloak-admin:
    {{- if $existing }}
      {{ index $existing.data "keycloak-admin" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
  store-pass:
    {{- if $existing }}
      {{ index $existing.data "store-pass" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
{{- end }}