{{- $existing := lookup "v1" "Secret" $.Release.Namespace (printf "%s-env" .Values.marketplace.generatePasswords.secretName) }}
{{- if .Values.marketplace.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.marketplace.generatePasswords.secretName }}-env
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  MONGO_BAE_BELP_PW:
    {{- if $existing }}
      {{ index $existing.data "MONGO_BAE_BELP_PW" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
  MONGO_BAE_CHARGING_PW:
    {{- if $existing }}
      {{ index $existing.data "MONGO_BAE_CHARGING_PW" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
{{- end }}