{{- $existing := lookup "v1" "Secret" $.Release.Namespace .Values.marketplace.generatePasswords.secretName }}
{{- if .Values.marketplace.generatePasswords.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.marketplace.generatePasswords.secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "dsc.labels" . | nindent 4 }}
data:
  mongodb-root-password:
    {{- if $existing }}
      {{ index $existing.data "mongodb-root-password" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
  mongodb-password:
    {{- if $existing }}
      {{ index $existing.data "mongodb-password" | quote }}
    {{- else }}
      {{ randAlphaNum 30 | b64enc | quote }}
    {{- end }}
{{- end }}